### ISSUE TITLE
Contribute DSA questions in any language

### ISSUE THREAD

**Issue by ritikpillai** [ritikpillai/FestAgain_2024#15]

**Comment by ritikpillai** [comment]
Its open to all, you can add!!

**Comment by skanarul8002** [comment]
**DSA Question: Find Maximum Element in Every Sliding Window of Size K**
**Description:** _Implement a solution to find the maximum element in every sliding window of size K for a given array of integers. This is a commonly asked interview problem in coding assessments and competitive programming, aimed at testing proficiency with data structures like queues or deques._

**Comment by Moumita-08** [comment]
Hii @ritikpillai , I'm interested in solving this issue. I can add problems like 'Tower of Hanoi' in C language. Can you assign me?
