### ISSUE TITLE
Contribute Web Technologies

### ISSUE THREAD

**Issue by ritikpillai** [ritikpillai/FestAgain_2024#18]

**Comment by Moumita-08** [comment]
Hey @ritikpillai I want to contribute in this issue. Can you assign it to me?

**Comment by ritikpillai** [comment]
Yeah please, go ahead!

**Comment by anukalp2804** [comment]
Hi @ritikpillai , I’m participating in Hacktoberfest 2025 and would love to contribute to this issue. Could you please assign it to me?
