### ISSUE TITLE
Merge two sorted linked lists

### ISSUE THREAD

**Issue by Nikhil-gi** [ritikpillai/FestAgain_2024#22]
Hello @ritikpillai 

I would like to work on solving the DSA problem "Merge Two Sorted Linked Lists," where two already sorted linked lists are merged into one sorted list. Please assign this issue to me under the hacktoberfest and hacktoberfest2024 label.
Feel free to modify further if needed!

**Comment by ritikpillai** [comment]
Sure, go head!!
