### ISSUE TITLE
Create a common Java folder for all .java files

### ISSUE THREAD

**Issue by sanvviratthore** [ritikpillai/FestAgain_2024#75]
Hi Ritik I hope you're doing well, I just came across your project and i feel there's a little we can modify. The java files have been written outside a common java folder. I would like to create a common JAVA Folder for other contributors to add their code inside it and would make sure the existing .java files are inside it. 

Why is it required: It would make the project more clear and precise. Would help people understand the code quickly and easily. 

Thankyou for reading!

**Comment by ritikpillai** [comment]
That's a wonderful suggestion. Please feel free to go ahead and make any appropriate changes as required!
